apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netflix-app
  name: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - image: ijeawele/netflix-app:latest
        name: netflix-app
        resources: {}
status: {}
